### ISSUE TITLE
was working fine with esxi 7.0 but not with 7.0.2 anymore

### ISSUE THREAD

**Issue by gehkah** [Napsty/check_esxi_hardware#55]
Traceback (most recent call last):
File "/usr/lib/nagios/plugins/check_esxi_hardware.py", line 785, in except pywbem._exceptions.ConnectionError as args: AttributeError: 'module' object has no attribute '_exceptions'

any ideas how to fix it?

**Comment by Napsty** [comment]
Hi @gehkah , thanks for the report.
I installed a new virtual ESXi 7.0.2, enabled CIM Server and can't reproduce this error.

```
$ python3 check_esxi_hardware.py -H 192.168.15.111 -U root -P Secret123. -v
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
20210525 12:09:15 LCD Status: True
20210525 12:09:15 Chassis Intrusion Status: True
20210525 12:09:15 Connection to https://192.168.15.111
20210525 12:09:15 Found pywbem version 1.2.0
20210525 12:09:15 Check classe OMC_SMASHFirmwareIdentity
20210525 12:09:15   Element Name = System BIOS
20210525 12:09:15     VersionString = VMW71.00V.16722896.B64.2008100651
20210525 12:09:15 Check classe CIM_Chassis
20210525 12:09:16   Element Name = Chassis
20210525 12:09:16     Manufacturer = No Enclosure
20210525 12:09:16     SerialNumber = VMware-56 4d 4a bc 57 47 6b de-f2 ef c5 90 7e 44 e2 28
20210525 12:09:16     Model = VMware7,1
20210525 12:09:16     Element Op Status = 0
20210525 12:09:16 Check classe CIM_Card
20210525 12:09:16   Element Name = Unknown
20210525 12:09:16     Element Op Status = 0
20210525 12:09:16 Check classe CIM_ComputerSystem
20210525 12:09:16   Element Name = localhost
20210525 12:09:16 Check classe CIM_NumericSensor
20210525 12:09:16 Check classe CIM_Memory
20210525 12:09:16   Element Name = Memory
20210525 12:09:16 Check classe CIM_Processor
20210525 12:09:16   Element Name = CPU 0
20210525 12:09:16     Family = 2
20210525 12:09:16     CurrentClockSpeed = 3426MHz
20210525 12:09:16     Element Op Status = 2
20210525 12:09:16   Element Name = CPU 1
20210525 12:09:16     Family = 2
20210525 12:09:16     CurrentClockSpeed = 3426MHz
20210525 12:09:16     Element Op Status = 2
20210525 12:09:16 Check classe CIM_RecordLog
20210525 12:09:16 Check classe OMC_DiscreteSensor
20210525 12:09:16 Check classe OMC_Fan
20210525 12:09:17 Check classe OMC_PowerSupply
20210525 12:09:17 Check classe VMware_StorageExtent
20210525 12:09:17 Check classe VMware_Controller
20210525 12:09:17 Check classe VMware_StorageVolume
20210525 12:09:17 Check classe VMware_Battery
20210525 12:09:17 Check classe VMware_SASSATAPort
OK - Server: No Enclosure VMware7,1 s/n: VMware-56 4d 4a bc 57 47 6b de-f2 ef c5 90 7e 44 e2 28 System BIOS: VMW71.00V.16722896.B64.2008100651 2020-08-10
```

Versions: Linux Mint 20.1 (based on Ubuntu 20.04), Python 3.8.5, pywbem 1.2.0, ESXi 7.0.2

Please share additional information concerning the used versions and also server (hardware) related information.

**Comment by gr0mit1** [comment]
Hi 
I can reproduce:

root@apps:/usr/lib/nagios/plugins# ./check_esxi_hardware.py -H xxxxxxxx -U root -P xxxxxx --verbose
20210724 19:08:48 LCD Status: True
20210724 19:08:48 Chassis Intrusion Status: True
20210724 19:08:48 Connection to https://xxxxxxxxxxxxxxx
20210724 19:08:48 Found pywbem version 0.8.3
20210724 19:08:48 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "./check_esxi_hardware.py", line 785, in <module>
    except pywbem._exceptions.ConnectionError as args:
AttributeError: 'module' object has no attribute '_exceptions'
root@apps:/usr/lib/nagios/plugins#

This is a brand new ESXI box Version: 7.0 Update 2

I get the same issue on Version: 6.7.0 Update 2 (Build 13981272)

Happy to help debug this but am not a Python expert - so will need some handholding.
Cheers.

**Comment by Napsty** [comment]
@gr0mit1 Did you try it with a newer pywbem version?

**Comment by Napsty** [comment]
I recently (in August) did some larger compatibility testing with newer and older ESXi versions.
See https://www.claudiokuenzler.com/blog/1110/check_esxi_hardware-esxi-compatibility-matrix-list
The mentioned errors could be related to pywbem. Please update to the newest pywbem version in this case.
