### ISSUE TITLE
Connection error after ESXi upgrade

### ISSUE THREAD

**Issue by fvb-sb** [Napsty/check_esxi_hardware#58]
Dear community

After upgrading my ESXi hosts from 6.7.0, 17700523 to 7.0.3, 18644231 the check_esxi_hardware script doesn't work anymore. CLI output is:

> 20211027 15:21:47 LCD Status: True
> 20211027 15:21:47 Chassis Intrusion Status: True
> 20211027 15:21:47 Connection to https://xxx.xxx.xx
> 20211027 15:21:47 Found pywbem version 0.7.0
> 20211027 15:21:47 Connection error, disable SSL certificate verification (probably patched pywbem)
> 20211027 15:21:47 Check classe OMC_SMASHFirmwareIdentity
> Traceback (most recent call last):
>   File "./check_esxi_hardware.py", line 790, in <module>
>     except pywbem._exceptions.ConnectionError as args:
> AttributeError: 'module' object has no attribute '_exceptions'

I've tried updating pywbem as well. Since then CLI output has changed but still no success:

> 20211027 15:27:35 LCD Status: True
> 20211027 15:27:35 Chassis Intrusion Status: True
> 20211027 15:27:35 Connection to https://xxx.xxx.xx
> 20211027 15:27:35 Found pywbem version 1.2.0
> 20211027 15:27:35 Check classe OMC_SMASHFirmwareIdentity
> Traceback (most recent call last):
>   File "./check_esxi_hardware.py", line 780, in <module>
>     instance_list = wbemclient.EnumerateInstances(classe)
>   File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 2783, in EnumerateInstances
>     PropertyList=PropertyList)
>   File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 1824, in _imethodcall
>     self, request_data, cimxml_headers)
>   File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 389, in wbem_request
>     raise AuthError(msg, conn_id=conn.conn_id)
> pywbem._exceptions.AuthError: WBEM server returned HTTP status 401 (Unauthorized). This is most likely an issue with userid/password, but for servers that implement resource access control it might also be an issue with the permissions of the userid.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./check_esxi_hardware.py", line 781, in <module>
>     except pywbem.cim_operations.CIMError as args:
> AttributeError: module 'pywbem' has no attribute 'cim_operations'

I've one ESXi node left running on 6.7. For this node the script still works like a charm. Any ideas what could do the trick?

OS: CentOS7
pywbem: 0.7.0 / 1.2.0
Version of check_esxi_hardware.py: 20210809
Executed command: check_esxi_hardware.py -H HOSTNAME -U USERNAME -P PASSWORD -V dell -v

Any help appreciated. Thanks in advance.
Sebastian

**Comment by fvb-sb** [comment]
It turned out that the permission of the monitoring user on the ESXi hosts were changed somehow due to the upgrade from ESXi 6.7 to 7.0. After applying administrative rights to the monitoring user the check_esxi_hardware.py script works as before/expected.

**Comment by ls440** [comment]
Hi is there any way that we check with no ssl certificate

**Comment by Napsty** [comment]
tcp/5989 is the CIM server with SSL/TLS certificate (wbem-https).
The alternative is tcp/5988 which is the CIM server without encryption (wbem-http). But I'm not sure if this is enabled or can be enabled on ESXi side. And even if it were possible, I strongly advise against using it, as your login credentials would be transmitted in plain text.

**Comment by ls440** [comment]
yes i disabled on esxi CIM secure server, i.e 5989, but still i am having issues 
UNKNOWN: 'Connection to "IP" timed out. (connect timeout=9.99)'
